# Generated by Django 4.2.7 on 2025-12-19 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ApprovalRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('request_type', models.CharField(choices=[('return', 'Product Return'), ('discount', 'Discount Override'), ('ad_hoc_item', 'Ad-hoc Item'), ('price_override', 'Price Override'), ('void_sale', 'Void Sale')], max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('details', models.JSONField(help_text='Request-specific details (item info, reason, amounts, etc.)')),
                ('reason', models.TextField()),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('resolution_notes', models.TextField(blank=True)),
                ('reference_id', models.CharField(blank=True, help_text='Sale ID, return ID, etc.', max_length=100)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
