# Generated by Django 4.2.7 on 2025-12-22 09:23

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0005_add_etims_qr_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saleitem',
            name='tax_rate',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5),
        ),
    ]
