# Generated by Django 4.2.7 on 2025-12-19 08:42

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('opening_time', models.DateTimeField(auto_now_add=True)),
                ('closing_time', models.DateTimeField(blank=True, null=True)),
                ('opening_cash', models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('closing_cash', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('expected_cash', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('cash_difference', models.DecimalField(blank=True, decimal_places=2, help_text='Positive=overage, Negative=shortage', max_digits=15, null=True)),
                ('status', models.CharField(choices=[('open', 'Open'), ('closed', 'Closed')], default='open', max_length=20)),
                ('total_sales', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('total_transactions', models.IntegerField(default=0)),
                ('notes', models.TextField(blank=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='shifts', to='core.branch')),
                ('cashier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='shifts', to=settings.AUTH_USER_MODEL)),
                ('closed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='closed_shifts', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-opening_time'],
            },
        ),
        migrations.CreateModel(
            name='ShiftTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('payment_method', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sale', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sales.sale')),
                ('shift', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='shifts.shift')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['shift', '-created_at'], name='shifts_shif_shift_i_e75aa9_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='shift',
            index=models.Index(fields=['cashier', '-opening_time'], name='shifts_shif_cashier_481992_idx'),
        ),
        migrations.AddIndex(
            model_name='shift',
            index=models.Index(fields=['branch', 'status'], name='shifts_shif_branch__28fb2d_idx'),
        ),
        migrations.AddIndex(
            model_name='shift',
            index=models.Index(fields=['status', '-opening_time'], name='shifts_shif_status_b04514_idx'),
        ),
    ]
